### ISSUE TITLE
Idea: parse Jupiter swaps only based on the Jupiter Program's emitted `SwapEvent`-s

### ISSUE THREAD

**Issue by serejke** [jup-ag/instruction-parser#46]
### Overview
Current implementation searches and matches `Transfer`/`TransferChecked` instructions to extract `mint`, `amount` of each routing step.

A big maintenance requirement is to regularly update the registered list of supported  DEXes [SWAP_IN_OUT_ACCOUNTS_POSITION](https://github.com/jup-ag/instruction-parser/blob/main/src/constants.ts#L65-L64), which is used to identify each DEX's positions of `in` and `out` token accounts.

### Proposal
Since Jupiter [program](https://solscan.io/account/JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4) emits an Anchor's `SwapEvent` after each routing step, one can utilize the reported values to determine the `amm` / `inputMint` / `inputAmount` / `outputMint` / `outputAmount`, which are enough for the Jupiter parser's result.

### Advantages
- There will be no need to maintain `SWAP_IN_OUT_ACCOUNTS_POSITION` mapping
- The resulting code will be more straightforward

### Open Question
Are there any corner cases that cannot be covered with the proposed approach?

**Comment by serejke** [comment]
@jokrsec as an author of #31, could you remind me what was the goal of the PR? You mentioned `So that the swap and fee events in the program can be removed` but is it the goal still and why? The current implementation of the parser is complex and requires regular maintenance. Besides that, it does not support upgrades of the DEX programs: imagine a DEX starts to receive input/output accounts in a different order starting from block #285713211, currently there is no mechanism in place to switch based on the block number. The most robust solution is to report the event from the Jupiter program.

**Comment by siong1987** [comment]
@serejke i reverted the code to use back event based parser. we may eventually remove events support from the program and hence the temporary experiments without.

**Comment by serejke** [comment]
@siong1987 what are the implications of reverting the code? do you think most of the parsing issues are resolved now?

Also could you explain why `force push` to the `main` branch was a good idea?

**Comment by serejke** [comment]
The parsing issues can be resolved in the new `main` branch after upgrading the Jupiter IDL to the latest version.

Effectively, the implementation of @jokrsec has been reverted via a `force-push` to the `main` branch (🤷 ).
